# ============================================================
# setup-edge-config.ps1
# Sets up Vercel Edge Config as the database for drg. Bunga app.
# Run: .\scripts\setup-edge-config.ps1
# ============================================================

Write-Host ""
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  drg. Bunga - Setup Vercel Edge Config Database" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Hanya 1 langkah yang diperlukan:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  1. Buka: https://vercel.com/account/tokens" -ForegroundColor White
Write-Host "  2. Klik [Create]" -ForegroundColor White
Write-Host "  3. Name: dental-bunga-db-write" -ForegroundColor White
Write-Host "  4. Scope: Full Account (atau pilih team reandyferdinantos-projects)" -ForegroundColor White
Write-Host "  5. Expiration: No Expiration" -ForegroundColor White
Write-Host "  6. Klik [Create Token] dan COPY tokennya" -ForegroundColor White
Write-Host ""

$VERCEL_API_TOKEN = Read-Host "Paste Vercel API Token kamu"

if (-not $VERCEL_API_TOKEN -or $VERCEL_API_TOKEN.Length -lt 10) {
    Write-Host "ERROR: Token tidak valid!" -ForegroundColor Red
    exit 1
}

$EDGE_CONFIG_ID = "ecfg_cteatktzu2dhtalvxahg2qws7dc2"
$TEAM_ID        = "team_Xq5vhluBUKtKfqVtFNG98Grb"

Write-Host ""
Write-Host "Test: Verifikasi akses ke Edge Config..." -ForegroundColor Yellow

try {
    $headers = @{ "Authorization" = "Bearer $VERCEL_API_TOKEN" }
    $resp = Invoke-RestMethod `
        -Uri "https://api.vercel.com/v1/edge-config/${EDGE_CONFIG_ID}?teamId=${TEAM_ID}" `
        -Headers $headers -Method GET
    Write-Host "  Edge Config ditemukan: $($resp.slug)" -ForegroundColor Green
} catch {
    Write-Host "  GAGAL akses Edge Config. Pastikan token benar dan punya akses ke team." -ForegroundColor Red
    Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Set env vars ke Vercel..." -ForegroundColor Yellow

Set-Location "$PSScriptRoot\.."

# Set VERCEL_API_TOKEN on Vercel
npx vercel env rm VERCEL_API_TOKEN production --yes 2>&1 | Out-Null
npx vercel env rm VERCEL_API_TOKEN preview --yes 2>&1 | Out-Null
npx vercel env rm VERCEL_API_TOKEN development --yes 2>&1 | Out-Null
$VERCEL_API_TOKEN | npx vercel env add VERCEL_API_TOKEN production preview development 2>&1 | Out-Null
Write-Host "  Set: VERCEL_API_TOKEN" -ForegroundColor Green

# Set EDGE_CONFIG_ID
npx vercel env rm EDGE_CONFIG_ID production --yes 2>&1 | Out-Null
npx vercel env rm EDGE_CONFIG_ID preview --yes 2>&1 | Out-Null
npx vercel env rm EDGE_CONFIG_ID development --yes 2>&1 | Out-Null
$EDGE_CONFIG_ID | npx vercel env add EDGE_CONFIG_ID production preview development 2>&1 | Out-Null
Write-Host "  Set: EDGE_CONFIG_ID" -ForegroundColor Green

# Set VERCEL_TEAM_ID
npx vercel env rm VERCEL_TEAM_ID production --yes 2>&1 | Out-Null
npx vercel env rm VERCEL_TEAM_ID preview --yes 2>&1 | Out-Null
npx vercel env rm VERCEL_TEAM_ID development --yes 2>&1 | Out-Null
$TEAM_ID | npx vercel env add VERCEL_TEAM_ID production preview development 2>&1 | Out-Null
Write-Host "  Set: VERCEL_TEAM_ID" -ForegroundColor Green

# Generate and set NEXTAUTH_SECRET
$NEXTAUTH_SECRET = -join ((48..57) + (97..122) | Get-Random -Count 64 | ForEach-Object { [char]$_ })
npx vercel env rm NEXTAUTH_SECRET production --yes 2>&1 | Out-Null
npx vercel env rm NEXTAUTH_SECRET preview --yes 2>&1 | Out-Null
npx vercel env rm NEXTAUTH_SECRET development --yes 2>&1 | Out-Null
$NEXTAUTH_SECRET | npx vercel env add NEXTAUTH_SECRET production preview development 2>&1 | Out-Null
Write-Host "  Set: NEXTAUTH_SECRET" -ForegroundColor Green

# Set NEXTAUTH_URL for production
"https://dental-appointment-bunga.vercel.app" | npx vercel env add NEXTAUTH_URL production 2>&1 | Out-Null
"http://localhost:3001" | npx vercel env add NEXTAUTH_URL development preview 2>&1 | Out-Null
Write-Host "  Set: NEXTAUTH_URL" -ForegroundColor Green

# Set admin credentials
"bunga@dentist.com" | npx vercel env add ADMIN_EMAIL production preview development 2>&1 | Out-Null
"admin123" | npx vercel env add ADMIN_PASSWORD production preview development 2>&1 | Out-Null
Write-Host "  Set: ADMIN_EMAIL + ADMIN_PASSWORD" -ForegroundColor Green

# Update .env.local
$envContent = @"
# Auto-generated by setup-edge-config.ps1
EDGE_CONFIG="https://edge-config.vercel.com/ecfg_cteatktzu2dhtalvxahg2qws7dc2?token=1050e8e0-b15c-41bb-8015-a826fa8c0803"
EDGE_CONFIG_ID="ecfg_cteatktzu2dhtalvxahg2qws7dc2"
VERCEL_API_TOKEN="$VERCEL_API_TOKEN"
VERCEL_TEAM_ID="team_Xq5vhluBUKtKfqVtFNG98Grb"
NEXTAUTH_SECRET="$NEXTAUTH_SECRET"
NEXTAUTH_URL="http://localhost:3001"
ADMIN_EMAIL="bunga@dentist.com"
ADMIN_PASSWORD="admin123"
"@

Set-Content -Path "$PSScriptRoot\..\.env.local" -Value $envContent -Encoding UTF8
Write-Host "  Updated: .env.local" -ForegroundColor Green

Write-Host ""
Write-Host "Deploy ke Vercel..." -ForegroundColor Yellow
npx vercel --prod --yes

Write-Host ""
Write-Host "==========================================================" -ForegroundColor Green
Write-Host "  SELESAI! Edge Config database siap digunakan." -ForegroundColor Green
Write-Host "  Setelah deploy, jalankan seed data:" -ForegroundColor Green
Write-Host "  fetch('/api/seed', {method:'POST'}) di browser console" -ForegroundColor Green
Write-Host "==========================================================" -ForegroundColor Green

